name: Install Node.js, Composer Packages, and Deploy via FTP

on: 
  push:
    branches:
      - main
      - master
      - '**'  # This will trigger on any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you want to use

    - name: Install Node.js packages
      run: |
        npm install # or yarn install

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Set to the directory you want to deploy
        server-dir: /htdocs/ # Set to the directory on your server where files should be uploaded
        port: ${{ secrets.FTP_PORT }} # Optional, if using a non-standard port
